### ISSUE TITLE
Deploy to Dev server

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#126]
```[tasklist]
### Tasks
- [x] Configure SQL Server database (see #12)
- [x] Configure site in IIS
- [x] Create Publish Profile
- [x] Create server-specific settings file
- [x] Test the deployment
```

**Comment by dougwaldron** [comment]
Ready for QA
