### ISSUE TITLE
Deploy to Staging server

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#127]
```[tasklist]
### Tasks
- [x] Configure SQL Server database (see #12)
- [x] Create server-specific settings file
- [x] Create Publish Profile
- [x] Configure site in IIS
- [x] Test the deployment
```
