### ISSUE TITLE
Deploy to Prod server

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#128]
```[tasklist]
### Tasks
- [x] Configure SQL Server database (see #12)
- [x] Create server-specific settings file
- [x] Create Publish Profile
- [x] Configure site in IIS
- [x] Deploy web app to server
- [x] Copy config files
- [x] Run the application
- [x] Run the data migration steps
- [x] Test the deployment
- [x] Send email to program
- [x] Publish IAIP update
```
