### ISSUE TITLE
Create data entity models

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#19]
See the [entity relationship diagram](https://github.com/gaepdit/sbeap/blob/ccee37cf615b478d6b957bcd09c2f91ac73269c7/docs/Entity%20relationship%20diagram.md) and refer to the [existing data tables](https://github.com/gaepdit/sbeap/discussions/16).

```[tasklist]
### Tasks
- [ ] https://github.com/gaepdit/sbeap/issues/60
- [ ] https://github.com/gaepdit/sbeap/issues/62
- [x] Create data model: Action Item
- [x] Create data model: Case
- [x] Create data model: Customer
- [x] Create data model: Contact
```

**Comment by dougwaldron** [comment]
For reference, here is a preliminary [entity diagram](https://github.com/gaepdit/sbeap/discussions/9).

Also, the existing [DB table structure](https://github.com/gaepdit/sbeap/discussions/16).
