### ISSUE TITLE
Tracking: Set up EF database repository

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#21]
Configure the Entity Framework `DbContext` and create repositories for each entity (see #19). Also add [seed data helpers](https://github.com/gaepdit/sbeap/blob/ac2fb80b0c17036420b67a8492cf3c37b2ae1858/src/EfRepository/Contexts/SeedDevData/DbSeedDataHelpers.cs) using the data from the `TestData` project.

```[tasklist]
- [ ] https://github.com/gaepdit/sbeap/issues/72
- [ ] https://github.com/gaepdit/sbeap/issues/73
- [ ] https://github.com/gaepdit/sbeap/issues/74
```

**Comment by dougwaldron** [comment]
Done!
