### ISSUE TITLE
Tracking: Implement Razor pages

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/sbeap#25]
Follow the workflow/site map from #24.

```[tasklist]
- [ ] https://github.com/gaepdit/sbeap/issues/59
- [ ] https://github.com/gaepdit/sbeap/issues/56
- [ ] https://github.com/gaepdit/sbeap/issues/76
- [ ] https://github.com/gaepdit/sbeap/issues/57
- [ ] https://github.com/gaepdit/sbeap/issues/58
- [ ] https://github.com/gaepdit/sbeap/issues/83
- [ ] https://github.com/gaepdit/sbeap/issues/82
- [ ] https://github.com/gaepdit/sbeap/issues/78
- [ ] https://github.com/gaepdit/sbeap/issues/86
- [ ] https://github.com/gaepdit/sbeap/issues/87
```

**Comment by dougwaldron** [comment]
Done!
